services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/config.yml
    volumes:
      - ./config/loki.yml:/etc/loki/config.yml
      - ./data/loki:/loki
    ports:
      - 3100:3100
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    user: "0"
    environment:
      - LOKI_ENABLE_API=true
